server:
  port: 9090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO:file:infra/config-server/repo}
          default-label: master
          search-paths: '{application}'

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: ${TRACING_SERVER_URL:http://localhost:9411/api/v2/spans}

logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"