version: '3.5'
services:
  discovery-server:
    image: alphonse-va/discovery-server
    container_name: discovery-server
    build:
      context: ./infra/discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep gradle  || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

  config-server:
    image: alphonse-va/config-server
    container_name: config-server
    build:
      context: ./infra/config-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      discovery-server:
        condition: service_healthy
    links:
      - discovery-server