spring:
  application:
    name: tracing-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9090/}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}

